In [1]:
!nvidia-smi

Mon Jan  6 01:07:56 2025       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.183.01             Driver Version: 535.183.01   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce GTX 1050 Ti     Off | 00000000:01:00.0 Off |                  N/A |
| N/A   49C    P8              N/A / ERR! |      4MiB /  4096MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.5.1+cu124


## introduction to tensors

create tensors
# scalar

In [2]:
scalar = torch.tensor(1)
scalar

tensor(1)

In [3]:
scalar.ndim

0

In [4]:
scalar.item()

1

In [5]:
##vector
vector = torch.tensor([1,1])
vector

tensor([1, 1])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
##Matrix
matrix = torch.tensor([[1,2],[4,5]])
matrix

tensor([[1, 2],
        [4, 5]])

In [9]:
#Tensor
tensor = torch.tensor([[
    [1,2,3],
    [4,5,6],
    [7,8,9]
]])
tensor

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [10]:
tensor.ndim

3

In [11]:
tensor.shape

torch.Size([1, 3, 3])

In [12]:
##Random Tensor
Random_tensor = torch.rand(3,4)
Random_tensor

tensor([[0.1070, 0.8996, 0.9464, 0.9665],
        [0.9458, 0.0712, 0.0267, 0.5666],
        [0.1588, 0.3691, 0.2033, 0.7296]])

In [13]:
 Random_tensor.ndim

2

In [14]:
Random_tensor.shape

torch.Size([3, 4])

In [15]:
##Image tensor
Image_Tensor = torch.rand(size=(3,244,244))
Image_Tensor

tensor([[[0.6534, 0.5241, 0.5966,  ..., 0.5669, 0.9506, 0.1440],
         [0.4414, 0.4199, 0.0083,  ..., 0.6780, 0.5571, 0.1435],
         [0.5865, 0.9206, 0.2763,  ..., 0.7606, 0.7253, 0.5787],
         ...,
         [0.0982, 0.8173, 0.6897,  ..., 0.8265, 0.2907, 0.1422],
         [0.8325, 0.4707, 0.2452,  ..., 0.5899, 0.8736, 0.1504],
         [0.5582, 0.0057, 0.4629,  ..., 0.2262, 0.9120, 0.6049]],

        [[0.4685, 0.8714, 0.0206,  ..., 0.5158, 0.6123, 0.2704],
         [0.3021, 0.8403, 0.8338,  ..., 0.6700, 0.2635, 0.0745],
         [0.9007, 0.3839, 0.3041,  ..., 0.0197, 0.7993, 0.4408],
         ...,
         [0.1385, 0.2946, 0.2635,  ..., 0.4782, 0.5158, 0.2905],
         [0.4756, 0.7659, 0.5161,  ..., 0.6834, 0.8219, 0.0591],
         [0.1707, 0.1637, 0.5385,  ..., 0.3131, 0.3723, 0.7833]],

        [[0.5920, 0.8773, 0.6680,  ..., 0.7431, 0.3490, 0.0529],
         [0.6119, 0.7129, 0.3074,  ..., 0.3899, 0.8753, 0.0803],
         [0.3749, 0.9539, 0.8504,  ..., 0.3332, 0.6847, 0.

In [16]:
##Tensor of zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [17]:
##Tensor of ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [18]:
ones.dtype

torch.float32

In [19]:
rang = torch.arange(0,11,2)
rang

tensor([ 0,  2,  4,  6,  8, 10])

In [20]:
Random_tensor * zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

### Tensor datatypes


There is three main datatypes float16 , float32 , float64

**Note**:U can run into three big issues in Tensor

1-not right datatype

2-not right shape

3-not right device

In [21]:
float_32_tensor = torch.tensor([3.0,6.0,9.0] , dtype=None , device=None , requires_grad=False)
float_32_tensor

tensor([3., 6., 9.])

In [22]:
float_32_tensor.dtype

torch.float32

In [23]:
float_16_tensor = float_32_tensor.type(torch.half)

In [24]:
float_16_tensor.dtype

torch.float16

In [25]:
float_32_tensor

tensor([3., 6., 9.])

In [26]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors 

**Note** :

1- to get datatype `tensor.dtype`

2- to get shape `tensor.shape`

3- to get device `tensor.device`

In [27]:
 #Create Tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.8194, 0.3358, 0.8927, 0.2258],
        [0.2658, 0.8188, 0.1268, 0.0287],
        [0.2238, 0.1553, 0.0175, 0.9183]])

In [28]:
##find info
print(some_tensor)
print(f"Datatype of tensor:{some_tensor.dtype} , shape of tensor:{some_tensor.shape}, device of tensor:{some_tensor.device}")

tensor([[0.8194, 0.3358, 0.8927, 0.2258],
        [0.2658, 0.8188, 0.1268, 0.0287],
        [0.2238, 0.1553, 0.0175, 0.9183]])
Datatype of tensor:torch.float32 , shape of tensor:torch.Size([3, 4]), device of tensor:cpu


## Mainpulating tensors (operations in tensor)

* Addition
* abstraction
* Divison
* Multiplication
* Matrix multiplication

In [29]:
tensor_operation = torch.rand(2,2,2)
tensor_operation + 10

tensor([[[10.4702, 10.3341],
         [10.7654, 10.8454]],

        [[10.7288, 10.8598],
         [10.3916, 10.4146]]])

In [30]:
tensor_operation * 10

tensor([[[4.7025, 3.3410],
         [7.6541, 8.4544]],

        [[7.2876, 8.5982],
         [3.9159, 4.1456]]])

In [31]:
tensor_operation / 2  

tensor([[[0.2351, 0.1671],
         [0.3827, 0.4227]],

        [[0.3644, 0.4299],
         [0.1958, 0.2073]]])

In [34]:
#Try PyTorch build-in function prefer using pure python for easy opearation
torch.mul(tensor_operation , 10)

tensor([[[4.7025, 3.3410],
         [7.6541, 8.4544]],

        [[7.2876, 8.5982],
         [3.9159, 4.1456]]])

# Matrix Multiplication

* Element * Matrix
* Dot product = Matrix *  Matrix

In [41]:
# Element wise multiplication
print(tensor , "*" , tensor)
print(f"Equale: {tensor * tensor}")

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]]) * tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
Equale: tensor([[[ 1,  4,  9],
         [16, 25, 36],
         [49, 64, 81]]])


In [70]:
# Matrix Multiplication
%%time
torch.matmul(tensor,tensor)

UsageError: Line magic function `%%time` not found.


In [39]:
tensor

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [43]:
# Matrix multiplication by hand
1*1 + 2*4 + 3*7

30

In [74]:
%%time
value = 0 
for i in range(len(tensor)):
    for j in range(len(tensor[i])):
        for z in range(len(tensor[i][j])):
            value =  tensor[i][j][z] * tensor[i][j][z]
            print(f"the Mult: {value}")

the Mult: 1
the Mult: 4
the Mult: 9
the Mult: 16
the Mult: 25
the Mult: 36
the Mult: 49
the Mult: 64
the Mult: 81
CPU times: user 4.53 ms, sys: 4.04 ms, total: 8.57 ms
Wall time: 5.45 ms
