In [1]:
!nvidia-smi

Mon Jan  6 01:07:56 2025       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.183.01             Driver Version: 535.183.01   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce GTX 1050 Ti     Off | 00000000:01:00.0 Off |                  N/A |
| N/A   49C    P8              N/A / ERR! |      4MiB /  4096MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [4]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.5.1+cu124


In [5]:
## introduction to tensors

###create tensors
###scalar

In [6]:
scalar = torch.tensor(1)
scalar

tensor(1)

In [7]:
scalar.ndim

0

In [8]:
scalar.item()

1

In [9]:
##vector
vector = torch.tensor([1,1])
vector

tensor([1, 1])

In [10]:
vector.ndim

1

In [11]:
vector.shape

torch.Size([2])

In [12]:
##Matrix
matrix = torch.tensor([[1,2],[4,5]])
matrix

tensor([[1, 2],
        [4, 5]])

In [13]:
#Tensor
tensor = torch.tensor([[
    [1,2,3],
    [4,5,6],
    [7,8,9]
]])
tensor

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [14]:
tensor.ndim

3

In [15]:
tensor.shape

torch.Size([1, 3, 3])

In [16]:
##Random Tensor
Random_tensor = torch.rand(3,4)
Random_tensor

tensor([[0.2481, 0.8099, 0.3794, 0.9714],
        [0.9175, 0.4101, 0.7195, 0.7888],
        [0.3289, 0.5077, 0.8387, 0.8127]])

In [17]:
 Random_tensor.ndim

2

In [18]:
Random_tensor.shape

torch.Size([3, 4])

In [19]:
##Image tensor
Image_Tensor = torch.rand(size=(3,244,244))
Image_Tensor

tensor([[[0.5887, 0.1619, 0.2863,  ..., 0.9069, 0.0460, 0.6396],
         [0.0093, 0.1698, 0.7250,  ..., 0.3200, 0.9653, 0.8060],
         [0.3723, 0.5430, 0.0036,  ..., 0.7721, 0.9511, 0.6120],
         ...,
         [0.9293, 0.3030, 0.6315,  ..., 0.1490, 0.5194, 0.5707],
         [0.7387, 0.2625, 0.8744,  ..., 0.2024, 0.0258, 0.2637],
         [0.2397, 0.0083, 0.9367,  ..., 0.7596, 0.6005, 0.5211]],

        [[0.1367, 0.1693, 0.7744,  ..., 0.9626, 0.0360, 0.4643],
         [0.8102, 0.8499, 0.3384,  ..., 0.7820, 0.7641, 0.7668],
         [0.5891, 0.2118, 0.1322,  ..., 0.7550, 0.4744, 0.3094],
         ...,
         [0.4803, 0.2448, 0.6114,  ..., 0.3049, 0.7045, 0.3663],
         [0.7270, 0.7923, 0.1987,  ..., 0.4853, 0.4790, 0.7047],
         [0.9110, 0.5794, 0.9976,  ..., 0.1362, 0.4959, 0.6614]],

        [[0.8183, 0.0488, 0.1181,  ..., 0.0974, 0.3369, 0.9621],
         [0.8096, 0.8681, 0.1022,  ..., 0.3231, 0.5727, 0.8283],
         [0.9623, 0.0773, 0.8936,  ..., 0.2265, 0.5148, 0.

In [20]:
##Tensor of zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [21]:
##Tensor of ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [22]:
ones.dtype

torch.float32

In [23]:
rang = torch.arange(0,11,2)
rang

tensor([ 0,  2,  4,  6,  8, 10])

In [24]:
Random_tensor * zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

### Tensor datatypes


There is three main datatypes float16 , float32 , float64

**Note**:U can run into three big issues in Tensor

1-not right datatype

2-not right shape

3-not right device

In [29]:
float_32_tensor = torch.tensor([3.0,6.0,9.0] , dtype=None , device=None , requires_grad=False)
float_32_tensor

tensor([3., 6., 9.])

In [30]:
float_32_tensor.dtype

torch.float32

In [43]:
float_16_tensor = float_32_tensor.type(torch.half)

In [44]:
float_16_tensor.dtype

torch.float16

In [45]:
float_32_tensor

tensor([3., 6., 9.])

In [46]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors 

**Note** :

1- to get datatype `tensor.dtype`

2- to get shape `tensor.shape`

3- to get device `tensor.device`

In [47]:
 #Create Tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.1413, 0.1503, 0.2332, 0.8732],
        [0.9252, 0.1250, 0.0722, 0.3976],
        [0.2004, 0.1759, 0.0538, 0.5580]])

In [48]:
##find info
print(some_tensor)
print(f"Datatype of tensor:{some_tensor.dtype} , shape of tensor:{some_tensor.shape}, device of tensor:{some_tensor.device}")

tensor([[0.1413, 0.1503, 0.2332, 0.8732],
        [0.9252, 0.1250, 0.0722, 0.3976],
        [0.2004, 0.1759, 0.0538, 0.5580]])
Datatype of tensor:torch.float32 , shape of tensor:torch.Size([3, 4]), device of tensor:cpu


## Mainpulating tensors (operations in tensor)

* Addition
* abstraction
* Divison
* Multiplication
* Matrix multiplication

In [60]:
tensor_operation = torch.rand(2,2,2)
tensor_operation + 10

tensor([[[10.9415, 10.8102],
         [10.1710, 10.3139]],

        [[10.1826, 10.4230],
         [10.0056, 10.9227]]])

In [61]:
tensor_operation * 10

tensor([[[9.4153, 8.1019],
         [1.7097, 3.1393]],

        [[1.8265, 4.2295],
         [0.0565, 9.2267]]])

In [62]:
tensor_operation / 2  

tensor([[[0.4708, 0.4051],
         [0.0855, 0.1570]],

        [[0.0913, 0.2115],
         [0.0028, 0.4613]]])

In [63]:
#Try PyTorch build-in function prefer using pure python for easy opearation
torch.mul(tensor_operation , 10)

tensor([[[9.4153, 8.1019],
         [1.7097, 3.1393]],

        [[1.8265, 4.2295],
         [0.0565, 9.2267]]])

In [64]:
torch.mm(tensor_operation,tensor_operation)

RuntimeError: self must be a matrix